name: Maven Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "maven"
  cancel-in-progress: true

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --show-version --no-transfer-progress --fail-at-end --batch-mode -Dstyle.color=always verify

      - name: Apply OpenRewrite recipes
        run: mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-testing-frameworks:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.testing.assertj.Assertj -Drewrite.exportDatatables=true

      - name: Verify still works
        run: mvn --show-version --no-transfer-progress --fail-at-end --batch-mode -Dstyle.color=always verify
